#  CE-40959: Deep Learning

# Numpy Tutorial

## Outline

1. Array
2. Array munipulation
3. Mathematical functions
4. Matrix compution
5. Saving and loading Numpy arrays

In [1]:
# importing numpy module into our notebook
import numpy as np

## 1. Array

In [2]:
a = np.array([1,2,3,4,5,6], dtype=np.int32)

print(type(a))
print(a.shape)   # tuple, array shape
print(a.ndim)    # int, number of array dimension
print(a.dtype)   # Data-type of the array’s elements
print(a.size)    # Number of elements in the array

<class 'numpy.ndarray'>
(6,)
1
int32
6


### 1.1 - Multi-Dimensional Arrays

In [3]:
a = np.random.rand(2,5,9,12)   # creates a 4d-array

# indexing 1 element
print(a[0,1,2,5]) 
print(a[0][1][2][5])

# shape and size
print(a.shape)
print(len(a))
print(a.shape[0], a.shape[1], a.shape[2], a.shape[3])
print(a.size)   

0.9769036540112375
0.9769036540112375
(2, 5, 9, 12)
2
2 5 9 12
1080


Other methods of array creation:

- `np.ones`
  
- `np.zeros`
  
- `np.full`
  
- `np.eye`
  
- `np.arange`
  
- `np.empty`
  
- `np.random.randint`, `np.random.rand`, `np.random.rand`, ...

In [4]:
a = np.zeros([2,3,4])
print(a.shape , a[0,0,0])

b = np.ones([5,3,7,2])
print('\n', b.shape , b[1,2,2,0])

c = np.full((2,7), 12)  # creates an array with shape (2, 7) and fills it with 12
print('\n', c.shape , c[0,0])

d = np.eye(4)
print('\n', d)

e = np.arange(1, 20, 3)
print('\n', e)

f = np.empty((2, 2, 2))  # with randomly initialized entries
print('\n', f)

(2, 3, 4) 0.0

 (5, 3, 7, 2) 1.0

 (2, 7) 12

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 [ 1  4  7 10 13 16 19]

 [[[2.33665620e-316 2.33444279e-316]
  [6.57148830e-299 1.60126796e-255]]

 [[1.00068322e+174 7.63813932e-270]
  [5.65631004e+303 2.29111235e+251]]]


In [5]:
# Initializing arrays like another array
a = np.random.rand(4, 6)
b = np.zeros_like(a)
print(b.shape)

c = np.empty_like(a)
print(c.shape)

(4, 6)
(4, 6)


In [6]:
# filling an array with a specific value
a = np.empty((2, 4))
a.fill(7)
print(a)

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]]


### 1.2 - Array indexing

In [7]:
a = np.random.rand(3,4,6,8)  # creates an array filled with values between (0, 1) coming from a uniform distribution

b = a[1:2, :3, 2:5, 1:6]
print('b: ', b)
print('b.shape: ', b.shape)

c = a[1]  # same as a[1,:,:,:]
print(c.shape)  

b:  [[[[0.30256942 0.05229005 0.38614748 0.75853977 0.03650009]
   [0.42848595 0.94977106 0.49748667 0.95214812 0.39835778]
   [0.51621256 0.85689435 0.93663902 0.44207387 0.36526788]]

  [[0.88307568 0.04371978 0.47481882 0.55714876 0.27904449]
   [0.94589868 0.7464737  0.10142841 0.91961247 0.76067102]
   [0.1918671  0.51704947 0.87263048 0.5185719  0.38641256]]

  [[0.96381828 0.50869932 0.02029039 0.99878281 0.65108041]
   [0.0959459  0.16205394 0.60052259 0.9609152  0.98950946]
   [0.06369711 0.76129398 0.08799424 0.86540315 0.97237176]]]]
b.shape:  (1, 3, 3, 5)
(4, 6, 8)


In [8]:
a = np.arange(10)
print(a)
print(a[2:5])
print(a[2:])
print(a[:-1])
print(a[2:20])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[2 3 4 5 6 7 8 9]


In [11]:
a = np.ones((5, 3, 2))
b = a[:,:,:, np.newaxis]
print(b.shape)
c = a[:,:, None]
print(c.shape)
print(a.shape)

(5, 3, 2, 1)
(5, 3, 1, 2)
(5, 3, 2)


### 1.3 - Masking and Clipping

In [18]:
a = np.random.randint(0, 10, (4, 4))
a

array([[2, 3, 5, 1],
       [7, 6, 6, 4],
       [4, 7, 3, 9],
       [6, 3, 4, 6]])

In [13]:
print(a == 5)  # masking

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [15]:
a[a==3] = 10
a

array([[10,  9,  6,  8],
       [ 6,  7,  8,  7],
       [ 9,  6,  0,  8],
       [ 0,  7,  8,  7]])

In [19]:
# clipping
c = np.minimum(a, 5)
print('c:\n', c)
d = np.maximum(a, 8)
print('d:\n', d)
e = np.clip(a, 2, 7)
print('e:\n', e)

c:
 [[2 3 5 1]
 [5 5 5 4]
 [4 5 3 5]
 [5 3 4 5]]
d:
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 9]
 [8 8 8 8]]
e:
 [[2 3 5 2]
 [7 6 6 4]
 [4 7 3 7]
 [6 3 4 6]]


#### 1.3.1 - Array masking based on a condition

In [20]:
a = np.random.randint(0, 6, (2,4))
print(a)

b = np.where(a>3, a ,a+10)  # return elements chosen from a or a+10 depending on condition.
print(b)

[[1 0 0 2]
 [5 3 3 4]]
[[11 10 10 12]
 [ 5 13 13  4]]


### 1.4 - Array conversion

In [21]:
# Converting an ndarray to list
a = np.arange(5)
print(a)
print(type(a))

b = a.tolist()
print(b)
print(type(b))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4]
<class 'list'>


In [22]:
# Casting
a = np.array([1.5, 2.34, 3.755, 4.513])
print(a.dtype)

b = a.astype(np.int32)
print(b)
print(b.dtype)

float64
[1 2 3 4]
int32


## 2. Array munipulation

### 2.1 - Reshape

In [23]:
a = np.random.randint(0,4,(3,4))

print(a.shape)     
print(a)

b = np.reshape(a,(2,6))
print(b.shape)
print(b)

(3, 4)
[[1 1 3 3]
 [2 3 2 2]
 [1 1 1 2]]
(2, 6)
[[1 1 3 3 2 3]
 [2 2 1 1 1 2]]


In [35]:
a = np.random.randint(0,10,(2,3,4))

print(a.shape)
print('a:\n', a)

a_ravel = np.ravel(a)  # create a 1d-array
print('a_ravel.shape: ', a_ravel.shape)
print('a_ravel:\n', a_ravel)

b = np.reshape(a,(-1))  # b is equal to a_ravel
print('b:\n', b)

(2, 3, 4)
a:
 [[[5 0 9 5]
  [8 9 8 7]
  [3 0 6 6]]

 [[6 2 1 1]
  [8 2 1 3]
  [6 8 4 4]]]
a_ravel.shape:  (24,)
a_ravel:
 [5 0 9 5 8 9 8 7 3 0 6 6 6 2 1 1 8 2 1 3 6 8 4 4]
b:
 [5 0 9 5 8 9 8 7 3 0 6 6 6 2 1 1 8 2 1 3 6 8 4 4]


### 2.2 - Transpose

In [36]:
a = np.random.rand(3,5)

a_t = a.T  # transposing
print(a_t.shape)

# reversing shape of multidimensional arrays 
b = np.random.rand(2,3,5)

b_t = b.T
print(b_t.shape)

(5, 3)
(5, 3, 2)


In [39]:
# using np.transpose
a = np.random.rand(2,3,5,7)

a_t = np.transpose(a,[1,3,0,2])

print(a_t.shape)

(3, 7, 2, 5)


### 2.3 - Combining arrays: Stacking & concatenation

In [40]:
# concatenation
a = np.random.randint(0, 5, (3,2,5))
b = np.random.randint(0 ,5, (3,4,5))
c = np.random.randint(0, 5, (3,6,5))

concat = np.concatenate((a,b,c), axis=1)
print(concat.shape)

(3, 12, 5)


In [55]:
# stacking
a = np.random.randint(0, 5, (3,4,5))
b = np.random.randint(0, 5, (3,4,5))
c = np.random.randint(0, 5, (3,4,5))

stack0 = np.stack([a, b, c], axis=0)
stack1 = np.stack([a, b, c], axis=1)
stack2 = np.stack([a, b, c], axis=2)
stack3 = np.stack((a, b, c), axis=3)

print(stack0.shape)
print(stack1.shape)
print(stack2.shape)
print(stack3.shape)

(3, 3, 4, 5)
(3, 3, 4, 5)
(3, 4, 3, 5)
(3, 4, 5, 3)


## 3. Mathematical functions

### 3.1 - Computation Along Axes

 - `np.sum()`
   
 - `np.mean()`
 

In [74]:
# np.sum
x = np.random.randint(0,4,(2,3)) 
x_sum = np.sum(x)
x_sum0 = np.sum(x, axis=0)
x_sum1 = np.sum(x, axis=1)
x_sum_keepdim = np.sum(x, axis=1, keepdims=True)

print(' x:\n', x, x.shape)
print('\n x_sum:\n', x_sum, x_sum.shape)
print('\n x_sum0:\n',x_sum0, x_sum0.shape)
print('\n x_sum1:\n', x_sum1, x_sum1.shape)
print('\n x_sum_keepdim:\n', x_sum_keepdim, x_sum_keepdim.shape)

 x:
 [[2 0 1]
 [0 0 0]] (2, 3)

 x_sum:
 3 ()

 x_sum0:
 [2 0 1] (3,)

 x_sum1:
 [3 0] (2,)

 x_sum_keepdim:
 [[3]
 [0]] (2, 1)


In [61]:
# np.mean
y = np.random.randint(1, 5, (3, 3))
y_mean = np.mean(y)
y_mean0 = np.mean(y, axis=0)
y_mean1 = np.mean(y, axis=1)
y_mean_keepdim = np.mean(y, axis=1, keepdims=True)

print('y:\n', y, y.shape)
print('\ny_mean:\n', y_mean, ', shape:', y_mean.shape)
print('\ny_mean0:\n', y_mean0, ', shape:', y_mean0.shape)
print('\ny_mean1:\n', y_mean1, ', shape:', y_mean1.shape)
print('\ny_mean_keepdims:\n', y_mean_keepdim, ', shape: ', y_mean_keepdim.shape)

y:
 [[3 1 4]
 [4 1 3]
 [2 4 3]] (3, 3)

y_mean:
 2.7777777777777777 , shape: ()

y_mean0:
 [3.         2.         3.33333333] , shape: (3,)

y_mean1:
 [2.66666667 2.66666667 3.        ] , shape: (3,)

y_mean_keepdims:
 [[2.66666667]
 [2.66666667]
 [3.        ]] , shape:  (3, 1)


### 3.2 - Arithmatic operations

In [64]:
x = np.arange(6).reshape(2,3) 
y = np.arange(3).reshape(3) 
m = np.multiply(x,y)
print('x:\n', x)
print('y:\n', y)
print('m:\n', m)

m1 = x * y  # overloaded operators
print('m1:\n', m1)

x_squared = x ** 2  # overloaded operators
print('x_squared:\n', x_squared)

x:
 [[0 1 2]
 [3 4 5]]
y:
 [0 1 2]
m:
 [[ 0  1  4]
 [ 0  4 10]]
m1:
 [[ 0  1  4]
 [ 0  4 10]]
x_squared:
 [[ 0  1  4]
 [ 9 16 25]]


In [75]:
x = np.arange(6).reshape(2,3) 
print(x)
y = np.arange(3)
print('\n', y)
print(x.shape, y.shape)
c = np.add(x,y)
print('\n', c)
c_1 = x + y  # overloaded operators
print('\n', c_1)

[[0 1 2]
 [3 4 5]]

 [0 1 2]
(2, 3) (3,)

 [[0 2 4]
 [3 5 7]]

 [[0 2 4]
 [3 5 7]]


## 4. Matrix multiplication

 - `np.dot(a, b)`
   
 - `np.matmul(a, b)`
   
 - `a.dot(b)`

In [66]:
a = np.arange(12).reshape(3,4)
b = np.arange(24).reshape(4,6)
a.dtype, b.dtype

(dtype('int64'), dtype('int64'))

In [67]:
c1 = np.dot(a,b)
c2 = a.dot(b)
print(c1 == c2)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [68]:
mat = np.matmul(a,b)  # if both a and b are 2-D arrays, this is preferred.
mat.shape

(3, 6)

##  5. Saving and loading Numpy array

### 5.1 - Saving and loading a single Numpy array

In [69]:
# Save single array
x = np.random.random((5,))
print(x)

np.save('tmp.npy', x)

[0.33029761 0.50138092 0.62367404 0.27681149 0.16207629]


In [71]:
import os
print(os.listdir() )  

['.ipynb_checkpoints', 'image', 'tmp.npy', 'data', 'HW1.ipynb', '.DS_Store', 'perceptron.py', 'Numpy Tutorial.ipynb', 'TensorFlow Tutorial.ipynb']


In [70]:
# Load the array
a = np.array
y = np.load('tmp.npy')

print(y)

[0.33029761 0.50138092 0.62367404 0.27681149 0.16207629]


### 5.2 - Saving and loading a dictionary of Numpy arrays

In [72]:
# Save dictionary of arrays
x1 = np.random.random((2,))
y1 = np.random.random((3,))
print(x1, y1)

np.savez('tmp.npz', x=x1, y=y1)



[0.57105561 0.78724259] [0.82399715 0.62856396 0.32186607]


In [73]:
# Load the dictionary of arrays
data = np.load('tmp.npz')

print(data['x'])
print(data['y'])

[0.57105561 0.78724259]
[0.82399715 0.62856396 0.32186607]


## References

 - https://docs.scipy.org/doc/numpy/reference/
 - http://deeplearning.cs.cmu.edu/